### ISSUE TITLE
Uncovered lines/branches

### ISSUE THREAD

**Issue by havencarlson** [nasa/MD#24]
**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/MD/blob/main/CONTRIBUTING.md).
* [X] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
- Fix #7: found instances of branches that can never be reached by unit tests.

**To Reproduce**
Functions with statements that can never be reached:

md_app.c: MD_ExecRequest
can't hit default case since command codes are already verified by `MD_SearchCmdHndlrTbl`
https://github.com/nasa/MD/blob/853c1e0e479d826f19ede093f0c38dbe6863014d/fsw/src/md_app.c#L666-L671

md_app.c: MD_SearchCmdHndlrTbl
can't reach this else statement because the message type can't be anything other than `MD_CMD_MSGTYPE `or `MD_TERM_MSGTYPE`
https://github.com/nasa/MD/blob/853c1e0e479d826f19ede093f0c38dbe6863014d/fsw/src/md_app.c#L761-L766

md_dwell_tbl.c: MD_TableValidationFunc
https://github.com/nasa/MD/blob/853c1e0e479d826f19ede093f0c38dbe6863014d/fsw/src/md_dwell_tbl.c#L145-L149

**Expected behavior**
100% coverage

**Code snips**
See above

**System observed on:**
CI

**Additional context**
None

**Reporter Info**
Haven Carlson, NASA

**Comment by skliper** [comment]
Note the first two would go away if command handling gets updated as part of this enhancement https://github.com/nasa/cFE/issues/2038, or could separate the functions (different c file) to stub and exercise error cases, or could include the HK request MID in the table (refactor to match TBL implementation).  Either way these are low risk since it's just defensive programming.  The else condition in the dwell table could just be replaced with a comment that there is no action for a case that isn't matched, also low risk.
